### ISSUE TITLE
Assalamu'alaikum - Login Password dan vendor assets tidak bisa update

### ISSUE THREAD

**Issue by cloner3000** [haifahrul/sippkm#1]
*untuk login admin nya apa mas? 
kemudian ada masalah di vendor /yii/asets tidak bsa update. terimkasih

**Comment by haifahrul** [comment]
@cloner3000 Login Super Admin username : `superadmin`, password : `superadmin`

**`/yii/aset`` tidak bsa update** karena folder asset di root tidak ada, silahkan bikin folder baru dengan nama `assets` di root direktori sippkm nya

**Comment by cloner3000** [comment]
Terimakasih sya coba dulu mas. boleh sya berkontribusi?

**Comment by cloner3000** [comment]
<img width="1234" alt="Screen Shot 2019-08-12 at 1 12 07 PM" src="https://user-images.githubusercontent.com/50857661/62848888-9db7cd00-bd07-11e9-8fc1-f2eb7359348b.png">
ini masih error mas.

**Comment by haifahrul** [comment]
> <img alt="Screen Shot 2019-08-12 at 1 12 07 PM" width="1234" src="https://user-images.githubusercontent.com/50857661/62848888-9db7cd00-bd07-11e9-8fc1-f2eb7359348b.png">
> 
> ini masih error mas.

sudah composer install mas?

**Comment by haifahrul** [comment]
> Terimakasih sya coba dulu mas. boleh sya berkontribusi?

boleh mas, yang ada tulisan **YARSI** hapus aja, dulu ini project buat mahasiswa soalnya.

**Comment by cloner3000** [comment]
sudah mas sudah composer install.
erornya ttp di situ. boleh mass

**Comment by haifahrul** [comment]
coba ini mas `composer global require "fxp/composer-asset-plugin:^1.2.0"`

baru `composer install` lagi

**Comment by cloner3000** [comment]
fix mas folder bower-assets di rubah jadi folder bower. trus untk role dosen dll. blm bs masuk

**Comment by haifahrul** [comment]
case close yah.

*trus untk role dosen dll. blm bs masuk* bikin issue baru aja
